name = "intelliseek"
compatibility_date = "2025-02-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "intellibase"
database_id = "3c222cd7-d868-48de-bd6d-9284135de817"
migrations_dir = "./src/db/migrations"

[[r2_buckets]]
bucket_name = "intellistore"
binding = "intellistore"

[vars]
NEXT_PUBLIC_BASE_URL = "https://intelliseek.pages.dev"
